#!/bin/bash

set -e

function generate_uuid () {
  uuidgen | tr '[A-F]' '[a-f]'
}

if [ "$1" = "" ]; then
  generate_uuid
  exit 0
fi

if [[ "$1" =~ ^[1-9][0-9]*$ ]]; then
  for i in $(seq $1); do generate_uuid; done
  exit 0
fi

echo "[WARN] Invalid argument."
echo "[WARN] The first argument should be a positive integer."
echo "[WARN] For example: genuuid 10"
exit 1
