#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
  echo "Pass a word to be replaced as the first argument."
  exit 1
fi

if [ -z "$2" ]; then
  echo "Pass a new word after replacement as the second argument."
  exit 1
fi

BEFORE_WORD="$1"
AFTER_WORD="$2"

ag -l "$BEFORE_WORD" | tee /dev/stderr | xargs sed -i'' "s/${BEFORE_WORD}/${AFTER_WORD}/g"

exit 0
